# Generated by Django 5.0.2 on 2024-09-18 09:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='_', max_length=1), size=9)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.boardstate')),
            ],
        ),
    ]
